 # Site settings
title: Your Blog
email: your@email.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourwebsite.com" # the base hostname & protocol for your site
twitter_username: username
github_username:  username
author_name: Your Name

# Build settings
markdown: kramdown
keep_files: ['.git']
permalink: /:title # => http://yoursite.com/post-title